### PR TITLE
Document some of the implementations as we discussed in Discussion #46

### PR DESCRIPTION
**Pull request by Aquaticat**
[Documentation about how the code is organized #46](https://github.com/run-z/run-z/discussions/46)

This pull request only documents some of what you said in the above discussion. This is supposed to be a preview for the style of my documentation, so I didn't document a lot of things.

Please **carefully** review those as I do not have lots of insight into the code. I tried, but one can only do so much when they're not the primary author and there's no documentation around that.

Also, I have found out some inconsistencies in the file structure. There are also some crucial user-facing info missing. There are some other issues.

Will open issues separately for those.

### CODE REVIEW

**Comment by surol** [comment]
Thanks!
The descriptions are correct.

**Comment by Aquaticat** [comment]
Hi @surol ,

Happy New Year!

I finally got some free time but I'm going to get busy again no later than Jan 10.

1.  Although the descriptions are correct, they are absolutely incomplete.
    Could you suggest changes to that?

2.  There is a `TODO:` inside `src/readme.md`. Could you check that?

3.  Are you satisfied with my style of documentation?
    I'm willing to change it if it doesn't fulfill your (project) requirements.

**Comment by surol** [comment]
Happy New Year, @Aquaticat!

I am absolutely satisfied.

The only unsatisfied person is [Codacy](https://app.codacy.com/gh/run-z/run-z/pullRequest?prid=8653933) that doesn't like extra spaces within Markdown.

**Comment by Aquaticat** [comment]
Haha. Actually, I was following [Google's Markdown styleguide](https://google.github.io/styleguide/docguide/style.html) so that's why I added these extra spaces. You reminded me to open an issue I forgot to open, that is, to specify a styleguide for Markdown documents in this project.

**Comment by Aquaticat** [comment]
You should look at that `TODO:`:

| Line number | Line content |
| --- | --- |
| 63 | `# Code that apply policy or rules` |
| 64 | `# TODO: ?` |
| 65 | `=-- <module-1>.rule.ts` |

`?` Means I'm not sure what it is, and I'm not sure what my own comment means as well.

**Comment by Aquaticat** [comment]
> The only unsatisfied person is [Codacy](https://app.codacy.com/gh/run-z/run-z/pullRequest?prid=8653933) that doesn't like extra spaces within Markdown.

You should probably configure Codacy to require extra spaces in lists. I have no idea how to configure it and I don't intend to learn about it, so you'll have to do it yourself.

**Comment by surol** [comment]
> You should look at that `TODO:`:
> Line number 	Line content
> 63 	`# Code that apply policy or rules`
> 64 	`# TODO: ?`
> 65 	`=-- <module-1>.rule.ts`
> 
> `?` Means I'm not sure what it is, and I'm not sure what my own comment means as well.

Added a (very sparse) description. Note that such files present only within `src/batches` directory.

**Comment by Aquaticat** [comment]
`src/batches` is not found. Did you mean `src/builtins/*batch*`

**Comment by Aquaticat** [comment]
It sure is very sparse. Describing `rule` with "rule" isn't clear.

Consider describing what the effect of the "rule" is commonly. If it is still unclear, consider adding some examples.

**Comment by surol** [comment]
I meant `src/core/batches`.
Now I also see the `*.rule.ts` files inside `builtins` too.
My bad.

Each of these files contain a `ZBatchRule` interface implementation.

**Comment by Aquaticat** [comment]
It is rather confusing what the `ZBatchRule` interface (found in `src/core/batches/batch-rule.ts`)'s comment is saying:

```typescript
/**
 * Batch processing rule.
 *
 * When rule {@link ZBatching.rule applied} to batching policy, a rule control instance is created for it.
 * Control instance interface contains methods updating batching policy.
 *
 * @typeparam TControl  A type of batch processing rule control.
 */
```

My suggestion is to enhance this comment and reference this file in the comment about `*.rule.ts`.

**Comment by surol** [comment]
I think the proper way would be to describe how the batching work... and right now I don't remember that. So I need some time to recall.

**Comment by Aquaticat** [comment]
I guess you could open an issue to remind yourself. Do you intend to use the GitHub issue tracker for stuff like this? If so, I'm going to open that issue.

**Comment by surol** [comment]
Yes, sure.

**Comment by Aquaticat** [comment]
Done: https://github.com/run-z/run-z/issues/60

**Pull request merged**
